// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7AnLvQbKm72YbWWxqOgT7zOAIBrsA4U',
    appId: '1:868136481797:web:313d1bb3a228b0f3b7d86c',
    messagingSenderId: '868136481797',
    projectId: 'edebiyat-soru',
    authDomain: 'edebiyat-soru.firebaseapp.com',
    storageBucket: 'edebiyat-soru.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoTMb8rJsmxsgcpmoNIGVhJk8kxJU4jQI',
    appId: '1:868136481797:android:e23df9274b3a68e7b7d86c',
    messagingSenderId: '868136481797',
    projectId: 'edebiyat-soru',
    storageBucket: 'edebiyat-soru.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-8zlYzwWX5YIQ2IIIjCoyQeZHqunOM0w',
    appId: '1:868136481797:ios:c7243743439fc4d5b7d86c',
    messagingSenderId: '868136481797',
    projectId: 'edebiyat-soru',
    storageBucket: 'edebiyat-soru.firebasestorage.app',
    iosBundleId: 'com.example.edebiyatSoru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-8zlYzwWX5YIQ2IIIjCoyQeZHqunOM0w',
    appId: '1:868136481797:ios:c7243743439fc4d5b7d86c',
    messagingSenderId: '868136481797',
    projectId: 'edebiyat-soru',
    storageBucket: 'edebiyat-soru.firebasestorage.app',
    iosBundleId: 'com.example.edebiyatSoru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi7AnLvQbKm72YbWWxqOgT7zOAIBrsA4U',
    appId: '1:868136481797:web:7f4ef126324b499ab7d86c',
    messagingSenderId: '868136481797',
    projectId: 'edebiyat-soru',
    authDomain: 'edebiyat-soru.firebaseapp.com',
    storageBucket: 'edebiyat-soru.firebasestorage.app',
  );
}
